### ISSUE TITLE
emsarray.open_dataset() of gbr1_2.0 data results in time access error

### ISSUE THREAD

**Issue by sspagnol** [csiro-coasts/emsarray#129]
Hi, wandering if anyone has any pointers on why the below snippet results in the errors shown.

'''
import emsarray
gbr1_url='http://dapds00.nci.org.au/thredds/dodsC/fx3/model_data/gbr1_2.0.ncml'
dataset = emsarray.open_dataset(gbr1_url)
'''

gives me

'''oc_open: server error retrieving url: code=2 message="The variable `time[0]' was not found in the dataset."oc_open: server error retrieving url: code=2 message=                                    "The variable `time[0]' was not found in the dataset."oc_open: server error retrieving url: code=2 message="The variable `time[0]' was not found in the dataset.                                    "oc_open: server error retrieving url: code=2 message="The variable `time[0]' was not found in the dataset."oc_open: server error retrieving url: code=2 message                                    ="The variable `time[0]' was not found in the dataset."oc_open: server error retrieving url: code=2 message="The variable `time[0]' was not found in the dataset                                    ."oc_open: server error retrieving url: code=2 message="The variable `time[0]' was not found in the dataset."Traceback (most recent call last):
'''

some stacktrace info and then

'''
RuntimeError: Failed to decode variable 'time': NetCDF: Access failure
'''

**Comment by sharon-tickell** [comment]
Hi @sspagnol :  can you please try again using a *https* URL for the GBR1_H2p0 OPeNDAP endpoint?  
(`https://dapds00.nci.org.au/thredds/dodsC/fx3/model_data/gbr1_2.0.ncml`)

The NCI upgraded their THREDDS server to be HTTPS by default a few years ago.  The HTML catalog pages have redirects so the old URLs still work, but the OPeNDAP protocol that emsarray is using under the hoold doesn't follow redirects

**Comment by sspagnol** [comment]
That was indeed the problem. Thanks!
