### ISSUE TITLE
Incorrect depth coordinate in UGrid dataset

### ISSUE THREAD

**Issue by mx-moth** [csiro-coasts/emsarray#138]
A UGrid dataset with two depth coordinates:

```
netcdf example {
dimensions:
	record = UNLIMITED ; // (64 currently)
	nMesh2_face = 9956 ;
	Mesh2_layers = 65 ;
	nMesh2_edge = 29937 ;
	Two = 2 ;
	nMaxMesh2_face_nodes = 8 ;
	nMesh2_face_links = 28347 ;
	Mesh2_layerfaces = 66 ;
	nMesh2_node = 19976 ;
variables:
	...
	double Mesh2_layerfaces(Mesh2_layerfaces) ;
		Mesh2_layerfaces:units = "metre" ;
		Mesh2_layerfaces:long_name = "Z coordinate at grid layer faces" ;
		Mesh2_layerfaces:coordinate_type = "Z" ;
	double Mesh2_layers(Mesh2_layers) ;
		Mesh2_layers:units = "metre" ;
		Mesh2_layers:long_name = "Z coordinate at grid layer centre" ;
		Mesh2_layers:coordinate_type = "Z" ;
		Mesh2_layers:positive = "up" ;
```

The two depth variables are equally as valid as depth coordinates as far as emsarray can tell. `dataset.ems.get_depth_name()` will return `"Mesh2_layerfaces"`, as the variables are processed in order and `Mesh2_layerfaces` happens to be first in this dataset. This causes problems when plotting transects, for example, which assumes the variable passed in for plotting is defined on the default depth coordinate.

Things to consider:

* In this case we could detect which is the cell coordinate and which is the boundary coordinate by examining the dimension sizes. Perhaps the coordinate with the smallest dimension size should be the 'default' depth coordinate?
* Perhaps the concept of a 'default' depth coordinate is invalid, as the depth coordinate depends on the data variable in question. Consider adding a `Convention.get_depth_coordinate_for_variable(variable)` function.
* Transect plotting should detect the correct depth coordinate to use for the variable passed in using the `Convention.get_coordinate_for_variable(variable)` so transects can be plotted for data on any depth coordinate.

**Comment by frizwi** [comment]
+1 for something in the Convention.
