### ISSUE TITLE
Example notebooks in the docs

### ISSUE THREAD

**Issue by mx-moth** [csiro-coasts/emsarray#3]
A place to discuss whether the example notebooks should be included in the documentation, or if they should be separated out.

The documentation should contain examples of how to use the library. The examples should be up-to-date, include code, prose explanation, and image outputs. The examples should use real-world data, such as the tutorial files. Notebooks meet all of these criteria.

Compiling notebooks as part of the documentation build has some downsides. It requires the build environment to have all of the optional dependencies installed, increasing install complexity and time. Jupyter notebooks are troublesome to version control well (although solutions like Jupytext help here). Using the tutorial files in the examples is good, but then requires downloading the tutorial files as part of the docs build process. Writing docs in notebooks is different to writing docs in reStructuredText files. The animation notebook example takes a few minutes to run. Including that in every docs build is an unpleasant concept. This example should not be a notebook in the docs.

Running and experimenting with the notebooks while they live in the docs is more complicated that when they live in say an `examples/` directory.

There is currently an issue with the plots generated by some example notebooks. Specifically, the coasts are incredibly low-detailed or missing entirely on some plots. This could be due to the parallel build and the coast file downloading?

![image](https://user-images.githubusercontent.com/132147/169203559-b7313442-f256-48ea-adca-d6f699be88e1.png)
![image](https://user-images.githubusercontent.com/132147/169203578-909ff189-6d84-450d-969d-150aacf5f555.png)

---

Alternate options:

* Move notebooks to `examples/`. This allows easier discovery, and does not require the notebooks to also serve as documentation in the same manner.
* Write examples as normal documentation pages, with precompiled assets. Possibly involve a `make` step that compiles a notebook-like file to code + assets? Investigate jupytext.

**Comment by hot007** [comment]
Hi @mx-moth , maybe this isn't appropriate as you really want the doco examples to be adjacent to the install on the user's local machine, but in terms of managing dependences do you think it's viable to connect this repo to Binder so that they can be interacted with from here? That might be a partial option at least?

**Comment by mx-moth** [comment]
Linking something like Binder to emsarray makes a lot of sense. If we make the docs examples normal documentation pages, and move the example notebooks to a separate folder, we can get the best of both worlds.

**Comment by mx-moth** [comment]
Notebooks have been moved to the [csiro-coasts/emsarray-notebooks repository](https://github.com/csiro-coasts/emsarray-notebooks/). This repository has been linked up with Binder so users can explore the notebooks online.
