### ISSUE TITLE
Allow for python <3.8?

### ISSUE THREAD

**Issue by blasee** [csiro-coasts/emsarray#7]
Hey @mx-moth,

Thanks again for developing this package. I'm running into the following error when importing `emsarray` using python 3.7:

```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_22943/494989257.py in <module>
----> 1 import emsarray
      3 """
      4 
----> 5 import importlib.metadata
      6 
      7 from . import tutorial

ModuleNotFoundError: No module named 'importlib.metadata'
```

It [turns out](https://stackoverflow.com/a/59734959) that `importlib` only has a `metadata` submodule starting from python 3.8. The `jsonschema` package uses the following code to circumvent this issue. 

```python
try:
    from importlib import metadata
except ImportError: # for Python<3.8
    import importlib_metadata as metadata
```

which of course requires the installation of the `importlib_metadata` package.

Is this something that could be implemented in `emsarray` too?

**Comment by sharon-tickell** [comment]
Noting for discussion that Python 3.7 will be [EOL in less than 12 months from now (on 2023-06-27)](https://devguide.python.org/versions/#versions)...    

I agree we should either support python 3.7 while it is still a supported version OR have a clear statement that we require python>=3.8.

If we're going to support 3.7 properly, though, then that would require _downgrading_  some of the emsarray dependencies, as several of the critical ones have already dropped python 3.7 support:

- [xarray](https://pypi.org/project/xarray/) latest is v2022.3.0, and the last version that supported python 3.7 was v0.20.2. emsarray requires v0.21.1, so requires python>=3.8.  It looks like the maintainers were [following the example of numpy, pandas and pyproj in dropping python 3.7 support](https://github.com/pydata/xarray/issues/6138)
- [pyproj](https://pypi.org/project/pyproj/) latest is v3.3.1 and the last version that supported python 3.7 was v3.2.1 (emsarray requires 3.3.0, so requires python>=3.8)
- [numpy](https://pypi.org/project/numpy/)  latest is v1.23.1, and the last version that supported python 3.7 was v1.21.6. (emsarray requirements currently have v1.21.4)
- [pandas](https://pypi.org/project/pandas/) latest is v1.4.3, and the last version that supported python 3.7 was v1.3.5 (emsarray requires v1.3.4)
- [scipy](https://pypi.org/project/scipy/) latest is v1.8.1, and the last version that supported python 3.7 was v1.7.3 (emsarray requires v1.7.3)

I'm reluctant to lock ourselves into older versions of things like xarray, as that would mean we can't take advantage of new features in that library as they're released (and also, security scanners get whiny about known vulnerabilities).   

@blasee what is your use case for needing python 3.7?   Any chance of a platform upgrade at your end?

**Comment by blasee** [comment]
@sharon-tickell I agree downgrading dependencies is not ideal at all. We certainly have the ability to upgrade python at our end so it seems that's the best option, I didn't quite realise how old 3.7 actually was. I'll close this issue, thanks for your reply!
